env:
  browser: true
  es2021: true
globals:
  process: true
  require: true
extends:
  - 'plugin:react/recommended'
  - "eslint:recommended"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
settings:
  react:
    version: "17.0.2"
rules:
  no-unused-vars: 1
  no-useless-escape: 0
  react/jsx-key: 1
  react/prop-types: 0
